# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: prod-file
        path: ./build

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
    - run: yarn install --frozen-lockfile
    - run: yarn test
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: prod-file
    #     path: ./build


  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: buildPath
          path: ./build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
